{% set name = "pybbi" %}
{% set version = "0.3.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "53b76ec07b558e404cf6e8421629b06814b97064bb047c030d64898884137ec3"

build:
  number: 0

requirements:
  host:
    - python>=3.4
    - pip
    - pkgconfig
    - numpy
    - six
    - cython
    - libclang
    - zlib
    - libpng
    - openssl
    - make
  run:
    - numpy
    - six
    - cython

test:
  imports:
    - bbi

about:
  home: "https://github.com/nvictus/pybbi"
  license: "MIT"
  license_family: "MIT"
  summary: "Python bindings to UCSC Big Binary (bigWig/bigBed) file library"

extra:
  recipe-maintainers:
    - Nanguage
